Import libraries

In [6]:
import pandas as pd
import numpy as np

import dataset

In [10]:
data_df=pd.read_csv(r"D:\University\year-3\3201-ML\Assignment-1\CCPP\Folds5x2_ppCSV.csv")
data_df.head()

AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

define x and y

In [11]:
x=data_df.drop(['PE'],axis=1).values
y=data_df['PE'].values

In [12]:
print(x)

[[   8.34   40.77 1010.84   90.01]
 [  23.64   58.49 1011.4    74.2 ]
 [  29.74   56.9  1007.15   41.91]
 ...
 [  15.99   43.34 1014.2    78.66]
 [  17.65   59.87 1018.58   94.65]
 [  23.68   51.3  1011.86   71.24]]


In [13]:
print(y)

[480.48 445.75 438.76 ... 465.96 450.93 451.67]


split the dataset in training set and test set

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

train the model on training set

In [17]:
from sklearn.linear_model import LinearRegression
ml=LinearRegression()
ml.fit(x_train,y_train)

LinearRegression()

predict the test set result

In [22]:
y_pred=ml.predict(x_test)
print(y_pred)

[433.31678099 448.38834579 445.91834991 ... 431.43297765 471.78247749
 426.15700131]


In [23]:
ml.predict([[8.34,40.77,1010.84,90.01]])

array([477.09098939])

evaluate model

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9286894372502137

plot the results

In [25]:
import matplotlib.pyplot as plt
plt.figure(figsize=(15,10))
plt.scatter(y_test,y_pred)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs. predicted')

Text(0.5, 1.0, 'Actual vs. predicted')

predicted values

In [27]:
pred_y_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_pred, 'Difference':y_test-y_pred})
pred_y_df[0:100]

Actual Value  Predicted Value  Difference
0         426.18       433.316781   -7.136781
1         451.10       448.388346    2.711654
2         442.87       445.918350   -3.048350
3         443.70       445.995905   -2.295905
4         460.59       462.798875   -2.208875
..           ...              ...         ...
95        468.86       465.884303    2.975697
96        480.35       474.890140    5.459860
97        432.36       436.018940   -3.658940
98        445.82       449.874962   -4.054962
99        449.12       445.854556    3.265444

[100 rows x 3 columns]