In [7]:
#load the library with theiris dataset
from sklearn.datasets import load_iris
#loading scikit srandom forest classifier library
from sklearn.ensemble import RandomForestClassifier
#loading pandas,
import pandas as pd
#loading numpy
import numpy as np
#setting random seed
np.random.seed(0)

In [13]:
#creating an object called iris with the iris data
iris = load_iris()
#print(iris)
#creating a dataframe with the four feature variables
df = pd.DataFrame(iris.data, columns=iris.feature_names)
#view top head 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
#adding a new column for the species name
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
#viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [20]:
#creating test and train data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
#viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa     False

In [21]:
#creating  dataframes with test rows and training rows
train, test = df[df['is_train']==True], df[df['is_train']==False]
#show the number of observations for the test and training dataframes
print('number of observation in the training  data: ',len(train))
print('number of observation in the testing  data: ',len(test))

number of observation in the training  data:  113
number of observation in the testing  data:  37


In [22]:
#create a list of the feature column's names
features = df.columns[:4]
#view features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [23]:
#converting each species name into digits
y = pd.factorize(train['species'])[0]
#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2], dtype=int64)

# start predicting

In [27]:
#creating a randon forest classifier
#n_jobs   <--- set the priorities
clf = RandomForestClassifier(n_jobs=2, random_state=0)
#training the classifier
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [29]:
#testing
#applying the trained classifier to the test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [33]:
#viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [36]:
#mapping names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]
#view the PREDICTED species for the first five observations
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [39]:
#viewing the ACTUAL species for the first five observations
test['species'].head()

1     setosa
4     setosa
9     setosa
18    setosa
21    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [41]:
#creating confusion matrix
pd.crosstab(test['species'], preds, rownames=['actual species'], colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
actual species                                  
setosa                 13           0          0
versicolor              0           7          1
virginica               0           1         15

In [48]:
#predict for data given by ourselves
preds = iris.target_names[clf.predict( [[5.0, 1.0, 0.4, 2.0],[5.0, 3.6, 1.4, 2.0]] )]
preds

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['setosa', 'setosa'], dtype='<U10')