In [1]:
#loading scikit random forest classifier library
from sklearn.ensemble import RandomForestClassifier
#loading pandas,
import pandas as pd
#loading numpy
import numpy as np
#setting random seed
np.random.seed(0)

In [2]:
#creating a dataframe with the four feature variables
df = pd.read_csv('data1.csv')
#view top head 5 rows
df.head()

age_years  sex_0male_1female  episode_number  hospital_outcome_1alive_0dead
0         21                  1               1                              1
1         20                  1               1                              1
2         21                  1               1                              1
3         77                  0               1                              1
4         72                  0               1                              1

In [3]:
#creating test and train data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
#viewing the top 5 rows
df.head()
#df[0:20]

age_years  sex_0male_1female  episode_number  \
0         21                  1               1   
1         20                  1               1   
2         21                  1               1   
3         77                  0               1   
4         72                  0               1   

   hospital_outcome_1alive_0dead  is_train  
0                              1      True  
1                              1      True  
2                              1      True  
3                              1      True  
4                              1      True

In [4]:
#creating  dataframes with test rows and training rows
train, test = df[df['is_train']==True], df[df['is_train']==False]
#show the number of observations for the test and training dataframes
print('number of observation in the training  data: ',len(train))
print('number of observation in the testing  data: ',len(test))

print('number of observation in the whole data set: ',len(df))

number of observation in the training  data:  82599
number of observation in the testing  data:  27605
number of observation in the whole data set:  110204


In [5]:
#create a list of the feature column's names
features = df.columns[:3]
#view features
features

Index(['age_years', 'sex_0male_1female', 'episode_number'], dtype='object')

In [6]:
#creating a randon forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
#training the classifier
clf.fit(train[features], train['hospital_outcome_1alive_0dead'])

RandomForestClassifier(n_jobs=2, random_state=0)

In [7]:
#testing
#applying the trained classifier to the test
clf.predict(test[features])

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [8]:
#viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[0.09023211, 0.90976789],
       [0.06896888, 0.93103112],
       [0.08998183, 0.91001817],
       [0.05032678, 0.94967322],
       [0.02456683, 0.97543317],
       [0.        , 1.        ],
       [0.03386705, 0.96613295],
       [0.01061346, 0.98938654],
       [0.02861295, 0.97138705],
       [0.01448089, 0.98551911]])

In [9]:
#view the PREDICTED value for the first five observations
preds = clf.predict(test[features])
preds[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [10]:
#viewing the ACTUAL value for the first five observations
test['hospital_outcome_1alive_0dead'].head()

7     1
8     1
10    1
13    1
17    1
Name: hospital_outcome_1alive_0dead, dtype: int64

In [11]:
#creating confusion matrix
pd.crosstab(test['hospital_outcome_1alive_0dead'], preds, rownames=['actual value'], colnames=['predicted value'])

predicted value  0      1
actual value             
0                1   2047
1                3  25554